### ISSUE TITLE
Add new team members to Website

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/capstone-coal.github.io#36]

**Comment by ghost** [comment]
This is as good a place to say hello as any. Welcome @bdegley4789 and @thomkenn to the COAL Capstone project. It was a privilege to work with JPL during my senior project and I'm sure that once all is said and done you will agree. I remain involved as an active volunteer, though it looks like we will be working on different things for the time being. My availability is limited, but you are welcome to contact me if I can be of assistance.

I am replying to this issue because the 2016-2017 contributor names are scattered throughout the source and documentation. The Python package [refers](https://github.com/capstone-coal/pycoal/blob/master/setup.py#L22) to "COAL Capstone Developers" which might be a more future-proof way to credit everyone, perhaps with a link to the [Team](https://capstone-coal.github.io/team) page. I would be willing to help update things if desired.

**Comment by bdegley4789** [comment]
Thank you for commenting on this. I don't think I had notifications for this organization turned on when this issue was created. That is great to hear that you are willing to help and volunteer on this project. I look forward to working with you!

I added my partner and myself to the team page in a pull request. I agree that is a good idea to just link to the team page to credit everyone who has worked on this project.
