### ISSUE TITLE
Errors when rendering Website

### ISSUE THREAD

**Issue by lewismc** [capstone-coal/capstone-coal.github.io#4]
Hi @xiaomei7 when I load the Website in my Firefox browser with Firebug activated, I get the following errors. Can you look into them please.
<img width="835" alt="screen shot 2017-02-02 at 11 21 49 am" src="https://cloud.githubusercontent.com/assets/1165719/22564590/ef8de2c6-e939-11e6-9743-0aa08466b493.png">

**Comment by ghost** [comment]
Can confirm with Firefox Developer Tools (Tools → Web Developer → Web Console).

The [mixed content](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) error is because the font link is `http` while the page is `https`.

The Bootstrap/jQuery error might be because jQuery is loaded after Bootstrap in the page source, or because the jQuery `$` variable is not exported where Bootstrap is looking for it.

**Comment by lewismc** [comment]
I am going to address this right now.

**Comment by lewismc** [comment]
@xiaomei7 the following file does not exist 
https://github.com/capstone-coal/capstone-coal.github.io/blob/master/index.html#L125

**Comment by lewismc** [comment]
I've just removed it.
